// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBpGsDw_bqcrbpEH-NWZkika5myMq7qW0',
    appId: '1:396242576287:web:de6849c3455e4b600313aa',
    messagingSenderId: '396242576287',
    projectId: 'eeayshopping',
    authDomain: 'eeayshopping.firebaseapp.com',
    storageBucket: 'eeayshopping.appspot.com',
    measurementId: 'G-TRKF734YHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1ajnMO5AuqqSkM7jPTKhL5UbP1uJJ8JE',
    appId: '1:396242576287:android:302d543c493b0d950313aa',
    messagingSenderId: '396242576287',
    projectId: 'eeayshopping',
    storageBucket: 'eeayshopping.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2l3-U4NNqNdK7oMIRx0kDb8oxWH2tAmA',
    appId: '1:396242576287:ios:498556a04647a73f0313aa',
    messagingSenderId: '396242576287',
    projectId: 'eeayshopping',
    storageBucket: 'eeayshopping.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2l3-U4NNqNdK7oMIRx0kDb8oxWH2tAmA',
    appId: '1:396242576287:ios:cf1a9b5e8eb3e2270313aa',
    messagingSenderId: '396242576287',
    projectId: 'eeayshopping',
    storageBucket: 'eeayshopping.appspot.com',
    iosBundleId: 'com.example.eCommerceApp.RunnerTests',
  );
}
